version: '3'
services:
  backend-svc:
    container_name: backend
    restart: unless-stopped
    build:
      context: .
    environment:
      - NODE_ENV=development
      - STAGE=dev
    depends_on:
      - postgres
    ports:
      - 4000:4000
    # volumes:
    #   - ./backend:/app
    #   - /app/node_modules
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
      - POSTGRES_DB=dzen
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '4001:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  pgdata:
  pgadmin:
